package by.bookmarket.entity.book;

public enum Genre {
    FANTASY, ADVENTURE, ROMANCE, CONTEMPORARY, DYSTOPIAN, MYSTERY, HORROR, THRILLER, PARANORMAL, HISTORICAL_FICTION, SCIENCE_FICTION, MEMOIR, COOKING, ART, PERSONAL, DEVELOPMENT, MOTIVATION, HEALTH, HISTORY, TRAVEL, GUIDE, HUMOR, CHILDRENS, EDUCATION
}
